### ISSUE TITLE
有规则改变时候，规则刷新失效，不能加载新的规则

### ISSUE THREAD

**Issue by CyanPZ** [411241940/dynamic-rule#1]
在本地起两个spring boot在其中一个修改了规则，另一个没有刷新，并且，再次修改，第一个也没有刷新新的规则，在类com.bin.rule.core.HandlerFactory的reloadHandler方法中加了以下代码，暂时解决
```
                HANDLER_INSTANCES.remove(name)
                HANDLER_INSTANCES.put(name, handler)
                BroadcasterFactory.broadcaster.watch(name)
```
![_20181224151548](https://user-images.githubusercontent.com/9296308/50393108-e299ee00-078e-11e9-9c35-e5227d8e5549.png)

**Comment by 411241940** [comment]
fixed
